version: '3'
services:
  app:
    build:
      context: .
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    command: "nodemon server.js"
  mysql:
    image: mysql:8.0
    volumes:
      - ./data/db:/var/lib/mysql
    restart: always
    ports:
      - "3006:3306"
    environment:
      "MYSQL_DATABASE": "koa-library"
      "MYSQL_ROOT_PASSWORD": "ultr@Fox54"